CREATE ROLE BINHTV NOT IDENTIFIED;

-- System privileges granted to BINHTV
GRANT ADMINISTER ANY SQL TUNING SET TO BINHTV CONTAINER=ALL;
GRANT ADMINISTER DATABASE TRIGGER TO BINHTV CONTAINER=ALL;
BEGIN
SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE
  (GRANTEE_NAME   => 'BINHTV', 
   PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER',
   ADMIN_OPTION   => FALSE);
END;
/
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO BINHTV CONTAINER=ALL;
GRANT ADMINISTER SQL TUNING SET TO BINHTV CONTAINER=ALL;
GRANT ADVISOR TO BINHTV CONTAINER=ALL;
GRANT ALTER ANY ANALYTIC VIEW TO BINHTV CONTAINER=ALL;
GRANT ALTER ANY ASSEMBLY TO BINHTV CONTAINER=ALL;
GRANT ALTER ANY ATTRIBUTE DIMENSION TO BINHTV CONTAINER=ALL;
GRANT ALTER ANY CLUSTER TO BINHTV CONTAINER=ALL;
GRANT ALTER ANY CUBE TO BINHTV CONTAINER=ALL;
GRANT ALTER ANY CUBE BUILD PROCESS TO BINHTV CONTAINER=ALL;
GRANT ALTER ANY CUBE DIMENSION TO BINHTV CONTAINER=ALL;
GRANT ALTER ANY DIMENSION TO BINHTV CONTAINER=ALL;
GRANT ALTER ANY EDITION TO BINHTV CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'BINHTV',
  GRANT_OPTION => FALSE);
END;
/
GRANT ALTER ANY HIERARCHY TO BINHTV CONTAINER=ALL;
GRANT ALTER ANY INDEX TO BINHTV CONTAINER=ALL;
GRANT ALTER ANY INDEXTYPE TO BINHTV CONTAINER=ALL;
GRANT ALTER ANY LIBRARY TO BINHTV CONTAINER=ALL;
GRANT ALTER ANY MATERIALIZED VIEW TO BINHTV CONTAINER=ALL;
GRANT ALTER ANY MEASURE FOLDER TO BINHTV CONTAINER=ALL;
GRANT ALTER ANY MINING MODEL TO BINHTV CONTAINER=ALL;
GRANT ALTER ANY OPERATOR TO BINHTV CONTAINER=ALL;
GRANT ALTER ANY OUTLINE TO BINHTV CONTAINER=ALL;
GRANT ALTER ANY PROCEDURE TO BINHTV CONTAINER=ALL;
GRANT ALTER ANY ROLE TO BINHTV CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE,
  GRANTEE      => 'BINHTV',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE_SET,
  GRANTEE      => 'BINHTV',
  GRANT_OPTION => FALSE);
END;
/
GRANT ALTER ANY SEQUENCE TO BINHTV CONTAINER=ALL;
GRANT ALTER ANY SQL PROFILE TO BINHTV CONTAINER=ALL;
GRANT ALTER ANY SQL TRANSLATION PROFILE TO BINHTV CONTAINER=ALL;
GRANT ALTER ANY TABLE TO BINHTV CONTAINER=ALL;
GRANT ALTER ANY TRIGGER TO BINHTV CONTAINER=ALL;
GRANT ALTER ANY TYPE TO BINHTV CONTAINER=ALL;
GRANT ALTER DATABASE TO BINHTV CONTAINER=ALL;
GRANT ALTER LOCKDOWN PROFILE TO BINHTV CONTAINER=ALL;
GRANT ALTER PROFILE TO BINHTV CONTAINER=ALL;
GRANT ALTER RESOURCE COST TO BINHTV CONTAINER=ALL;
GRANT ALTER ROLLBACK SEGMENT TO BINHTV CONTAINER=ALL;
GRANT ALTER SESSION TO BINHTV CONTAINER=ALL;
GRANT ALTER SYSTEM TO BINHTV CONTAINER=ALL;
GRANT ALTER TABLESPACE TO BINHTV CONTAINER=ALL;
GRANT ALTER USER TO BINHTV CONTAINER=ALL;
GRANT ANALYZE ANY TO BINHTV CONTAINER=ALL;
GRANT ANALYZE ANY DICTIONARY TO BINHTV CONTAINER=ALL;
GRANT AUDIT ANY TO BINHTV CONTAINER=ALL;
GRANT AUDIT SYSTEM TO BINHTV CONTAINER=ALL;
GRANT BACKUP ANY TABLE TO BINHTV CONTAINER=ALL;
GRANT BECOME USER TO BINHTV CONTAINER=ALL;
GRANT CHANGE NOTIFICATION TO BINHTV CONTAINER=ALL;
GRANT COMMENT ANY MINING MODEL TO BINHTV CONTAINER=ALL;
GRANT COMMENT ANY TABLE TO BINHTV CONTAINER=ALL;
GRANT CREATE ANALYTIC VIEW TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY ANALYTIC VIEW TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY ASSEMBLY TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY ATTRIBUTE DIMENSION TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY CLUSTER TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY CONTEXT TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY CREDENTIAL TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY CUBE TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY CUBE BUILD PROCESS TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY CUBE DIMENSION TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY DIMENSION TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY DIRECTORY TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY EDITION TO BINHTV CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'BINHTV',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE ANY HIERARCHY TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY INDEX TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY INDEXTYPE TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY JOB TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY LIBRARY TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY MATERIALIZED VIEW TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY MEASURE FOLDER TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY MINING MODEL TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY OPERATOR TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY OUTLINE TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY PROCEDURE TO BINHTV CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE,
  GRANTEE      => 'BINHTV',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE_SET,
  GRANTEE      => 'BINHTV',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE ANY SEQUENCE TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY SQL PROFILE TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY SQL TRANSLATION PROFILE TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY SYNONYM TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY TABLE TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY TRIGGER TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY TYPE TO BINHTV CONTAINER=ALL;
GRANT CREATE ANY VIEW TO BINHTV CONTAINER=ALL;
GRANT CREATE ASSEMBLY TO BINHTV CONTAINER=ALL;
GRANT CREATE ATTRIBUTE DIMENSION TO BINHTV CONTAINER=ALL;
GRANT CREATE CLUSTER TO BINHTV CONTAINER=ALL;
GRANT CREATE CREDENTIAL TO BINHTV CONTAINER=ALL;
GRANT CREATE CUBE TO BINHTV CONTAINER=ALL;
GRANT CREATE CUBE BUILD PROCESS TO BINHTV CONTAINER=ALL;
GRANT CREATE CUBE DIMENSION TO BINHTV CONTAINER=ALL;
GRANT CREATE DATABASE LINK TO BINHTV CONTAINER=ALL;
GRANT CREATE DIMENSION TO BINHTV CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_EVALUATION_CONTEXT_OBJ,
  GRANTEE      => 'BINHTV',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE EXTERNAL JOB TO BINHTV CONTAINER=ALL;
GRANT CREATE HIERARCHY TO BINHTV CONTAINER=ALL;
GRANT CREATE INDEXTYPE TO BINHTV CONTAINER=ALL;
GRANT CREATE JOB TO BINHTV CONTAINER=ALL;
GRANT CREATE LIBRARY TO BINHTV CONTAINER=ALL;
GRANT CREATE LOCKDOWN PROFILE TO BINHTV CONTAINER=ALL;
GRANT CREATE MATERIALIZED VIEW TO BINHTV CONTAINER=ALL;
GRANT CREATE MEASURE FOLDER TO BINHTV CONTAINER=ALL;
GRANT CREATE MINING MODEL TO BINHTV CONTAINER=ALL;
GRANT CREATE OPERATOR TO BINHTV CONTAINER=ALL;
GRANT CREATE PLUGGABLE DATABASE TO BINHTV CONTAINER=ALL;
GRANT CREATE PROCEDURE TO BINHTV CONTAINER=ALL;
GRANT CREATE PROFILE TO BINHTV CONTAINER=ALL;
GRANT CREATE PUBLIC DATABASE LINK TO BINHTV CONTAINER=ALL;
GRANT CREATE PUBLIC SYNONYM TO BINHTV CONTAINER=ALL;
GRANT CREATE ROLE TO BINHTV CONTAINER=ALL;
GRANT CREATE ROLLBACK SEGMENT TO BINHTV CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_OBJ,
  GRANTEE      => 'BINHTV',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_SET_OBJ,
  GRANTEE      => 'BINHTV',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE SEQUENCE TO BINHTV CONTAINER=ALL;
GRANT CREATE SESSION TO BINHTV CONTAINER=ALL;
GRANT CREATE SQL TRANSLATION PROFILE TO BINHTV CONTAINER=ALL;
GRANT CREATE SYNONYM TO BINHTV CONTAINER=ALL;
GRANT CREATE TABLE TO BINHTV CONTAINER=ALL;
GRANT CREATE TABLESPACE TO BINHTV CONTAINER=ALL;
GRANT CREATE TRIGGER TO BINHTV CONTAINER=ALL;
GRANT CREATE TYPE TO BINHTV CONTAINER=ALL;
GRANT CREATE USER TO BINHTV CONTAINER=ALL;
GRANT CREATE VIEW TO BINHTV CONTAINER=ALL;
GRANT DEBUG ANY PROCEDURE TO BINHTV CONTAINER=ALL;
GRANT DEBUG CONNECT SESSION TO BINHTV CONTAINER=ALL;
GRANT DELETE ANY CUBE DIMENSION TO BINHTV CONTAINER=ALL;
GRANT DELETE ANY MEASURE FOLDER TO BINHTV CONTAINER=ALL;
GRANT DELETE ANY TABLE TO BINHTV CONTAINER=ALL;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'DEQUEUE_ANY',
  GRANTEE      => 'BINHTV',
  ADMIN_OPTION => FALSE);
END;
/
GRANT DROP ANY ANALYTIC VIEW TO BINHTV CONTAINER=ALL;
GRANT DROP ANY ASSEMBLY TO BINHTV CONTAINER=ALL;
GRANT DROP ANY ATTRIBUTE DIMENSION TO BINHTV CONTAINER=ALL;
GRANT DROP ANY CLUSTER TO BINHTV CONTAINER=ALL;
GRANT DROP ANY CONTEXT TO BINHTV CONTAINER=ALL;
GRANT DROP ANY CUBE TO BINHTV CONTAINER=ALL;
GRANT DROP ANY CUBE BUILD PROCESS TO BINHTV CONTAINER=ALL;
GRANT DROP ANY CUBE DIMENSION TO BINHTV CONTAINER=ALL;
GRANT DROP ANY DIMENSION TO BINHTV CONTAINER=ALL;
GRANT DROP ANY DIRECTORY TO BINHTV CONTAINER=ALL;
GRANT DROP ANY EDITION TO BINHTV CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'BINHTV',
  GRANT_OPTION => FALSE);
END;
/
GRANT DROP ANY HIERARCHY TO BINHTV CONTAINER=ALL;
GRANT DROP ANY INDEX TO BINHTV CONTAINER=ALL;
GRANT DROP ANY INDEXTYPE TO BINHTV CONTAINER=ALL;
GRANT DROP ANY LIBRARY TO BINHTV CONTAINER=ALL;
GRANT DROP ANY MATERIALIZED VIEW TO BINHTV CONTAINER=ALL;
GRANT DROP ANY MEASURE FOLDER TO BINHTV CONTAINER=ALL;
GRANT DROP ANY MINING MODEL TO BINHTV CONTAINER=ALL;
GRANT DROP ANY OPERATOR TO BINHTV CONTAINER=ALL;
GRANT DROP ANY OUTLINE TO BINHTV CONTAINER=ALL;
GRANT DROP ANY PROCEDURE TO BINHTV CONTAINER=ALL;
GRANT DROP ANY ROLE TO BINHTV CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE,
  GRANTEE      => 'BINHTV',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE_SET,
  GRANTEE      => 'BINHTV',
  GRANT_OPTION => FALSE);
END;
/
GRANT DROP ANY SEQUENCE TO BINHTV CONTAINER=ALL;
GRANT DROP ANY SQL PROFILE TO BINHTV CONTAINER=ALL;
GRANT DROP ANY SQL TRANSLATION PROFILE TO BINHTV CONTAINER=ALL;
GRANT DROP ANY SYNONYM TO BINHTV CONTAINER=ALL;
GRANT DROP ANY TABLE TO BINHTV CONTAINER=ALL;
GRANT DROP ANY TRIGGER TO BINHTV CONTAINER=ALL;
GRANT DROP ANY TYPE TO BINHTV CONTAINER=ALL;
GRANT DROP ANY VIEW TO BINHTV CONTAINER=ALL;
GRANT DROP LOCKDOWN PROFILE TO BINHTV CONTAINER=ALL;
GRANT DROP PROFILE TO BINHTV CONTAINER=ALL;
GRANT DROP PUBLIC DATABASE LINK TO BINHTV CONTAINER=ALL;
GRANT DROP PUBLIC SYNONYM TO BINHTV CONTAINER=ALL;
GRANT DROP ROLLBACK SEGMENT TO BINHTV CONTAINER=ALL;
GRANT DROP TABLESPACE TO BINHTV CONTAINER=ALL;
GRANT DROP USER TO BINHTV CONTAINER=ALL;
GRANT EM EXPRESS CONNECT TO BINHTV CONTAINER=ALL;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'ENQUEUE_ANY',
  GRANTEE      => 'BINHTV',
  ADMIN_OPTION => FALSE);
END;
/
GRANT EXECUTE ANY ASSEMBLY TO BINHTV CONTAINER=ALL;
GRANT EXECUTE ANY CLASS TO BINHTV CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'BINHTV',
  GRANT_OPTION => FALSE);
END;
/
GRANT EXECUTE ANY INDEXTYPE TO BINHTV CONTAINER=ALL;
GRANT EXECUTE ANY LIBRARY TO BINHTV CONTAINER=ALL;
GRANT EXECUTE ANY OPERATOR TO BINHTV CONTAINER=ALL;
GRANT EXECUTE ANY PROCEDURE TO BINHTV CONTAINER=ALL;
GRANT EXECUTE ANY PROGRAM TO BINHTV CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE,
  GRANTEE      => 'BINHTV',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE_SET,
  GRANTEE      => 'BINHTV',
  GRANT_OPTION => FALSE);
END;
/
GRANT EXECUTE ANY TYPE TO BINHTV CONTAINER=ALL;
GRANT EXECUTE ASSEMBLY TO BINHTV CONTAINER=ALL;
GRANT EXEMPT DDL REDACTION POLICY TO BINHTV CONTAINER=ALL;
GRANT EXEMPT DML REDACTION POLICY TO BINHTV CONTAINER=ALL;
GRANT EXPORT FULL DATABASE TO BINHTV CONTAINER=ALL;
GRANT FLASHBACK ANY TABLE TO BINHTV CONTAINER=ALL;
GRANT FLASHBACK ARCHIVE ADMINISTER TO BINHTV CONTAINER=ALL;
GRANT FORCE ANY TRANSACTION TO BINHTV CONTAINER=ALL;
GRANT FORCE TRANSACTION TO BINHTV CONTAINER=ALL;
GRANT GLOBAL QUERY REWRITE TO BINHTV CONTAINER=ALL;
GRANT GRANT ANY OBJECT PRIVILEGE TO BINHTV CONTAINER=ALL;
GRANT GRANT ANY PRIVILEGE TO BINHTV CONTAINER=ALL;
GRANT GRANT ANY ROLE TO BINHTV CONTAINER=ALL;
GRANT IMPORT FULL DATABASE TO BINHTV CONTAINER=ALL;
GRANT INSERT ANY CUBE DIMENSION TO BINHTV CONTAINER=ALL;
GRANT INSERT ANY MEASURE FOLDER TO BINHTV CONTAINER=ALL;
GRANT INSERT ANY TABLE TO BINHTV CONTAINER=ALL;
GRANT LOCK ANY TABLE TO BINHTV CONTAINER=ALL;
GRANT LOGMINING TO BINHTV CONTAINER=ALL;
GRANT MANAGE ANY FILE GROUP TO BINHTV CONTAINER=ALL;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'BINHTV',
  ADMIN_OPTION => FALSE);
END;
/
GRANT MANAGE FILE GROUP TO BINHTV CONTAINER=ALL;
GRANT MANAGE SCHEDULER TO BINHTV CONTAINER=ALL;
GRANT MANAGE TABLESPACE TO BINHTV CONTAINER=ALL;
GRANT MERGE ANY VIEW TO BINHTV CONTAINER=ALL;
GRANT ON COMMIT REFRESH TO BINHTV CONTAINER=ALL;
GRANT QUERY REWRITE TO BINHTV CONTAINER=ALL;
GRANT READ ANY FILE GROUP TO BINHTV CONTAINER=ALL;
GRANT READ ANY TABLE TO BINHTV CONTAINER=ALL;
GRANT REDEFINE ANY TABLE TO BINHTV CONTAINER=ALL;
GRANT RESTRICTED SESSION TO BINHTV CONTAINER=ALL;
GRANT RESUMABLE TO BINHTV CONTAINER=ALL;
GRANT SELECT ANY CUBE TO BINHTV CONTAINER=ALL;
GRANT SELECT ANY CUBE BUILD PROCESS TO BINHTV CONTAINER=ALL;
GRANT SELECT ANY CUBE DIMENSION TO BINHTV CONTAINER=ALL;
GRANT SELECT ANY DICTIONARY TO BINHTV CONTAINER=ALL;
GRANT SELECT ANY MEASURE FOLDER TO BINHTV CONTAINER=ALL;
GRANT SELECT ANY MINING MODEL TO BINHTV CONTAINER=ALL;
GRANT SELECT ANY SEQUENCE TO BINHTV CONTAINER=ALL;
GRANT SELECT ANY TABLE TO BINHTV CONTAINER=ALL;
GRANT SELECT ANY TRANSACTION TO BINHTV CONTAINER=ALL;
GRANT SET CONTAINER TO BINHTV CONTAINER=ALL;
GRANT UNDER ANY TABLE TO BINHTV CONTAINER=ALL;
GRANT UNDER ANY TYPE TO BINHTV CONTAINER=ALL;
GRANT UNDER ANY VIEW TO BINHTV CONTAINER=ALL;
GRANT UPDATE ANY CUBE TO BINHTV CONTAINER=ALL;
GRANT UPDATE ANY CUBE BUILD PROCESS TO BINHTV CONTAINER=ALL;
GRANT UPDATE ANY CUBE DIMENSION TO BINHTV CONTAINER=ALL;
GRANT UPDATE ANY TABLE TO BINHTV CONTAINER=ALL;
GRANT USE ANY JOB RESOURCE TO BINHTV CONTAINER=ALL;
GRANT USE ANY SQL TRANSLATION PROFILE TO BINHTV CONTAINER=ALL;

-- Roles granted to BINHTV
GRANT CAPTURE_ADMIN TO BINHTV CONTAINER=ALL;
GRANT DATAPUMP_EXP_FULL_DATABASE TO BINHTV CONTAINER=ALL;
GRANT DATAPUMP_IMP_FULL_DATABASE TO BINHTV CONTAINER=ALL;
GRANT EM_EXPRESS_ALL TO BINHTV CONTAINER=ALL;
GRANT EXECUTE_CATALOG_ROLE TO BINHTV CONTAINER=ALL;
GRANT EXP_FULL_DATABASE TO BINHTV CONTAINER=ALL;
GRANT GATHER_SYSTEM_STATISTICS TO BINHTV CONTAINER=ALL;
GRANT IMP_FULL_DATABASE TO BINHTV CONTAINER=ALL;
GRANT JAVA_ADMIN TO BINHTV CONTAINER=ALL;
GRANT JAVA_DEPLOY TO BINHTV CONTAINER=ALL;
GRANT OLAP_BINHTV TO BINHTV CONTAINER=ALL;
GRANT OLAP_XS_ADMIN TO BINHTV CONTAINER=ALL;
GRANT OPTIMIZER_PROCESSING_RATE TO BINHTV CONTAINER=ALL;
GRANT SCHEDULER_ADMIN TO BINHTV CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE TO BINHTV CONTAINER=ALL;
GRANT WM_ADMIN_ROLE TO BINHTV CONTAINER=ALL;
GRANT XBINHTVDMIN TO BINHTV CONTAINER=ALL;
GRANT XDB_SET_INVOKER TO BINHTV CONTAINER=ALL;

-- Grantees of BINHTV
GRANT BINHTV TO BINHTV;
GRANT BINHTV TO OAZ8_3;
GRANT BINHTV TO SYS WITH ADMIN OPTION CONTAINER=ALL;
GRANT BINHTV TO SYSTEM CONTAINER=ALL;
GRANT BINHTV TO TEACH_A;
GRANT BINHTV TO TEACH_B;
GRANT BINHTV TO TEACH_C;
GRANT BINHTV TO TEACH_D;