CREATE ROLE role20 NOT IDENTIFIED;

--dba 

-- Object privileges granted to role20
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.X$PT46MP5MEPA004NE0KWN0SK0K1LN TO role20;
GRANT EXECUTE ON ORDSYS.CARTRIDGE TO role20 ;
GRANT EXECUTE ON SYS.ADR_HOME_T TO role20 ;
GRANT EXECUTE ON SYS.ADR_INCIDENT_CORR_KEYS_T TO role20 ;
GRANT EXECUTE ON SYS.ADR_INCIDENT_FILES_T TO role20 ;
GRANT EXECUTE ON SYS.ADR_INCIDENT_INFO_T TO role20 ;
GRANT EXECUTE ON SYS.ADR_INCIDENT_T TO role20 ;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_ARGS_T TO role20 ;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_ARG_T TO role20 ;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_ECID_T TO role20 ;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_ERRID_T TO role20 ;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_SUPPL_ATTRS_T TO role20 ;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_SUPPL_ATTR_T TO role20 ;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_T TO role20 ;
GRANT EXECUTE ON SYS.AS_REPLAY TO role20 ;
GRANT SELECT ON SYS.CDB_XS_ACTIVE_SESSIONS TO role20 ;
GRANT SELECT ON SYS.CDB_XS_SESSIONS TO role20 ;
GRANT SELECT ON SYS.CDB_XS_SESSION_NS_ATTRIBUTES TO role20 ;
GRANT SELECT ON SYS.CDB_XS_SESSION_ROLES TO role20 ;
GRANT DELETE, INSERT, SELECT, UPDATE ON SYS.DBA_REGISTRY_SQLPATCH TO role20 ;
GRANT DELETE, INSERT, SELECT, UPDATE ON SYS.DBA_REGISTRY_SQLPATCH_RU_INFO TO role20 ;
GRANT SELECT ON SYS.DBA_XS_ACTIVE_SESSIONS TO role20 ;
GRANT SELECT ON SYS.DBA_XS_SESSIONS TO role20 ;
GRANT SELECT ON SYS.DBA_XS_SESSION_NS_ATTRIBUTES TO role20 ;
GRANT SELECT ON SYS.DBA_XS_SESSION_ROLES TO role20 ;
GRANT EXECUTE ON SYS.DBMS_ADR TO role20 ;
GRANT EXECUTE ON SYS.DBMS_ADR_APP TO role20 ;
GRANT EXECUTE ON SYS.DBMS_APP_CONT TO role20 ;
GRANT EXECUTE ON SYS.DBMS_APP_CONT_ADMIN TO role20 ;
GRANT EXECUTE ON SYS.DBMS_AUTO_INDEX TO role20 ;
GRANT EXECUTE ON SYS.DBMS_AUTO_SQLTUNE TO role20 ;
GRANT EXECUTE ON SYS.DBMS_AUTO_TASK_ADMIN TO role20 ;
GRANT EXECUTE ON SYS.DBMS_AUTO_TASK_IMMEDIATE TO role20 ;
GRANT EXECUTE ON SYS.DBMS_AWR_WAREHOUSE_SERVER TO role20 ;
GRANT EXECUTE ON SYS.DBMS_AWR_WAREHOUSE_SOURCE TO role20 ;
GRANT EXECUTE ON SYS.DBMS_CACHEUTIL TO role20 ;
GRANT EXECUTE ON SYS.DBMS_DNFS TO role20 ;
GRANT EXECUTE ON SYS.DBMS_FEATURE_USAGE_REPORT TO role20 ;
GRANT EXECUTE ON SYS.DBMS_FLASHBACK TO role20 ;
GRANT EXECUTE ON SYS.DBMS_FLASHBACK_ARCHIVE TO role20 ;
GRANT EXECUTE ON SYS.DBMS_FS TO role20 ;
GRANT EXECUTE ON SYS.DBMS_GSM_FIX TO role20 ;
GRANT EXECUTE ON SYS.DBMS_HANG_MANAGER TO role20 ;
GRANT EXECUTE ON SYS.DBMS_HM TO role20 ;
GRANT EXECUTE ON SYS.DBMS_ILM_ADMIN TO role20 ;
GRANT EXECUTE ON SYS.DBMS_INMEMORY_ADMIN TO role20 ;
GRANT EXECUTE ON SYS.DBMS_IR TO role20 ;
GRANT EXECUTE ON SYS.DBMS_LOGSTDBY TO role20 ;
GRANT EXECUTE ON SYS.DBMS_MANAGEMENT_BOOTSTRAP TO role20 ;
GRANT EXECUTE ON SYS.DBMS_MEMOPTIMIZE_ADMIN TO role20 ;
GRANT EXECUTE ON SYS.DBMS_MONITOR TO role20 ;
GRANT EXECUTE ON SYS.DBMS_NETWORK_ACL_ADMIN TO role20 ;
GRANT EXECUTE ON SYS.DBMS_PERF TO role20 ;
GRANT EXECUTE ON SYS.DBMS_RAT_MASK TO role20 ;
GRANT EXECUTE ON SYS.DBMS_RESULT_CACHE TO role20 ;
GRANT EXECUTE ON SYS.DBMS_RESUMABLE TO role20 ;
GRANT EXECUTE ON SYS.DBMS_ROLLING TO role20 ;
GRANT EXECUTE ON SYS.DBMS_SERVER_ALERT TO role20 ;
GRANT EXECUTE ON SYS.DBMS_SERVER_TRACE TO role20 ;
GRANT EXECUTE ON SYS.DBMS_SERVICE TO role20 ;
GRANT EXECUTE ON SYS.DBMS_SERVICE_CONST TO role20 ;
GRANT EXECUTE ON SYS.DBMS_SERVICE_ERR TO role20 ;
GRANT EXECUTE ON SYS.DBMS_SERVICE_PRVT TO role20 ;
GRANT EXECUTE ON SYS.DBMS_STORAGE_MAP TO role20 ;
GRANT EXECUTE ON SYS.DBMS_TDB TO role20 ;
GRANT EXECUTE ON SYS.DBMS_TNS TO role20 ;
GRANT EXECUTE ON SYS.DBMS_UADV_ARR TO role20 ;
GRANT EXECUTE ON SYS.DBMS_UMF TO role20 ;
GRANT EXECUTE ON SYS.DBMS_UNDO_ADV TO role20 ;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_CAPTURE TO role20 ;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPLAY TO role20 ;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPOSITORY TO role20 ;
GRANT EXECUTE ON SYS.DBMS_WRR_STATE TO role20 ;
GRANT EXECUTE ON SYS.DBMS_XS_PRINCIPALS TO role20 ;
GRANT EXECUTE ON SYS.GRANT_RDF_OWNER_DR_PRIVS TO role20 ;
GRANT EXECUTE ON SYS.HM_SQLTK_INTERNAL TO role20 ;
GRANT EXECUTE ON SYS.LOAD_UNDO_STAT TO role20 ;
GRANT DELETE, INSERT, SELECT, UPDATE ON SYS.MAP_OBJECT TO role20 ;
GRANT EXECUTE ON SYS.OJDS_CONTEXT TO role20 ;
GRANT EXECUTE ON SYS.ORD_ADMIN TO role20 ;
GRANT EXECUTE ON SYS.OUTLN_PKG TO role20 ;
GRANT EXECUTE ON SYS.RDF_NETWORK_CREATOR_PRIVS TO role20 ;
GRANT EXECUTE ON SYS.RESET_UNDO_STAT TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_ADR_CONTROL TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_ADR_CONTROL_AUX TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_ADR_INVALIDATION TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_ALERT_EXT TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_AMS_XACTION TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_DDE_USER_ACTION TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_DDE_USER_ACTION_DEF TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_DDE_USR_ACT_PARAM TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_DDE_USR_ACT_PARAM_DEF TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_DDE_USR_INC_ACT_MAP TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_DDE_USR_INC_TYPE TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_DFW_CONFIG_CAPTURE TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_DFW_CONFIG_ITEM TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_DFW_PATCH_CAPTURE TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_DFW_PATCH_ITEM TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_DFW_PURGE TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_DFW_PURGE_ITEM TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_DIAGV_INCIDENT TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_DIR_EXT TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_EM_DIAG_JOB TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_EM_TARGET_INFO TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_EM_USER_ACTIVITY TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_HM_FDG_SET TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_HM_FINDING TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_HM_INFO TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_HM_MESSAGE TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_HM_RECOMMENDATION TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_HM_RUN TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_INCCKEY TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_INCIDENT TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_INCIDENT_FILE TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_CONFIG TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_IMPT_DEF TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_INFO TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_PK_IMPTS TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_SUMMARY TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_IPS_CONFIGURATION TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_IPS_FILE_COPY_LOG TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_IPS_FILE_METADATA TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_IPS_PACKAGE TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_IPS_PACKAGE_FILE TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_IPS_PACKAGE_HISTORY TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_IPS_PACKAGE_INCIDENT TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_IPS_PKG_UNPACK_HIST TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_IPS_PROGRESS_LOG TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_IPS_REMOTE_PACKAGE TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_LOG_EXT TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_PDB_PROBLEM TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_PDB_SPACE_MGMT TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_PICKLEERR TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_PROBLEM TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_RELMD_EXT TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_SWEEPERR TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VADR_CONTROL TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VEM_USER_ACTLOG TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VEM_USER_ACTLOG1 TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VHM_RUN TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VIEW TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VIEWCOL TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VINCIDENT TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VINCIDENT_FILE TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VINC_METER_INFO TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VIPS_FILE_COPY_LOG TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VIPS_FILE_METADATA TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PACKAGE_FILE TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PACKAGE_HISTORY TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PACKAGE_MAIN_INT TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PACKAGE_SIZE TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_FILE TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_INC_CAND TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_INC_DTL TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_INC_DTL1 TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_MAIN_PROBLEM TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VNOT_EXIST_INCIDENT TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VPDB_PROBLEM TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM1 TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM2 TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_BUCKET TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_BUCKET1 TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_BUCKET_COUNT TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_INT TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_LASTINC TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VSHOWCATVIEW TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VSHOWINCB TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VSHOWINCB_I TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_VTEST_EXISTS TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_V_ACTINC TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_V_ACTPROB TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_V_INCCOUNT TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_V_INCFCOUNT TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_V_INC_METER_INFO_PROB TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_V_IPSPRBCNT TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_V_IPSPRBCNT1 TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_V_NFCINC TO role20 ;
GRANT SELECT ON SYS.V_$DIAG_V_SWPERRCOUNT TO role20 ;
GRANT INSERT, SELECT, UPDATE ON SYS.XSDB$SCHEMA_ACL TO role20 ;
GRANT EXECUTE ON SYS.XS_MTCACHE_INT TO role20 ;
GRANT EXECUTE ON XDB.DBMS_CSX_ADMIN TO role20 ;
GRANT EXECUTE ON XDB.DBMS_XDBT TO role20 ;
GRANT EXECUTE ON XDB.DBMS_XDB_ADMIN TO role20 ;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$ACL TO role20 ;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$CHECKOUTS TO role20 ;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$CONFIG TO role20 ;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$D_LINK TO role20 ;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$H_INDEX TO role20 ;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$H_LINK TO role20 ;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$NLOCKS TO role20 ;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$RESCONFIG TO role20 ;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$RESOURCE TO role20 ;

-- System privileges granted to role20
GRANT ADMINISTER ANY SQL TUNING SET TO role20 ;
GRANT ADMINISTER DATABASE TRIGGER TO role20 ;
BEGIN
SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE
  (GRANTEE_NAME   => 'role20', 
   PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER',
   ADMIN_OPTION   => FALSE);
END;
/
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO role20 ;
GRANT ADMINISTER SQL TUNING SET TO role20 ;
GRANT ADVISOR TO role20 ;
GRANT ALTER ANY ANALYTIC VIEW TO role20 ;
GRANT ALTER ANY ASSEMBLY TO role20 ;
GRANT ALTER ANY ATTRIBUTE DIMENSION TO role20 ;
GRANT ALTER ANY CLUSTER TO role20 ;
GRANT ALTER ANY CUBE TO role20 ;
GRANT ALTER ANY CUBE BUILD PROCESS TO role20 ;
GRANT ALTER ANY CUBE DIMENSION TO role20 ;
GRANT ALTER ANY DIMENSION TO role20 ;
GRANT ALTER ANY EDITION TO role20 ;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'role20',
  GRANT_OPTION => FALSE);
END;
/
GRANT ALTER ANY HIERARCHY TO role20 ;
GRANT ALTER ANY INDEX TO role20 ;
GRANT ALTER ANY INDEXTYPE TO role20 ;
GRANT ALTER ANY LIBRARY TO role20 ;
GRANT ALTER ANY MATERIALIZED VIEW TO role20 ;
GRANT ALTER ANY MEASURE FOLDER TO role20 ;
GRANT ALTER ANY MINING MODEL TO role20 ;
GRANT ALTER ANY OPERATOR TO role20 ;
GRANT ALTER ANY OUTLINE TO role20 ;
GRANT ALTER ANY PROCEDURE TO role20 ;
GRANT ALTER ANY ROLE TO role20 ;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE,
  GRANTEE      => 'role20',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE_SET,
  GRANTEE      => 'role20',
  GRANT_OPTION => FALSE);
END;
/
GRANT ALTER ANY SEQUENCE TO role20 ;
GRANT ALTER ANY SQL PROFILE TO role20 ;
GRANT ALTER ANY SQL TRANSLATION PROFILE TO role20 ;
GRANT ALTER ANY TABLE TO role20 ;
GRANT ALTER ANY TRIGGER TO role20 ;
GRANT ALTER ANY TYPE TO role20 ;
GRANT ALTER DATABASE TO role20 ;
GRANT ALTER LOCKDOWN PROFILE TO role20 ;
GRANT ALTER PROFILE TO role20 ;
GRANT ALTER RESOURCE COST TO role20 ;
GRANT ALTER ROLLBACK SEGMENT TO role20 ;
GRANT ALTER SESSION TO role20 ;
GRANT ALTER SYSTEM TO role20 ;
GRANT ALTER TABLESPACE TO role20 ;
GRANT ALTER USER TO role20 ;
GRANT ANALYZE ANY TO role20 ;
GRANT ANALYZE ANY DICTIONARY TO role20 ;
GRANT AUDIT ANY TO role20 ;
GRANT AUDIT SYSTEM TO role20 ;
GRANT BACKUP ANY TABLE TO role20 ;
GRANT BECOME USER TO role20 ;
GRANT CHANGE NOTIFICATION TO role20 ;
GRANT COMMENT ANY MINING MODEL TO role20 ;
GRANT COMMENT ANY TABLE TO role20 ;
GRANT CREATE ANALYTIC VIEW TO role20 ;
GRANT CREATE ANY ANALYTIC VIEW TO role20 ;
GRANT CREATE ANY ASSEMBLY TO role20 ;
GRANT CREATE ANY ATTRIBUTE DIMENSION TO role20 ;
GRANT CREATE ANY CLUSTER TO role20 ;
GRANT CREATE ANY CONTEXT TO role20 ;
GRANT CREATE ANY CREDENTIAL TO role20 ;
GRANT CREATE ANY CUBE TO role20 ;
GRANT CREATE ANY CUBE BUILD PROCESS TO role20 ;
GRANT CREATE ANY CUBE DIMENSION TO role20 ;
GRANT CREATE ANY DIMENSION TO role20 ;
GRANT CREATE ANY DIRECTORY TO role20 ;
GRANT CREATE ANY EDITION TO role20 ;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'role20',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE ANY HIERARCHY TO role20 ;
GRANT CREATE ANY INDEX TO role20 ;
GRANT CREATE ANY INDEXTYPE TO role20 ;
GRANT CREATE ANY JOB TO role20 ;
GRANT CREATE ANY LIBRARY TO role20 ;
GRANT CREATE ANY MATERIALIZED VIEW TO role20 ;
GRANT CREATE ANY MEASURE FOLDER TO role20 ;
GRANT CREATE ANY MINING MODEL TO role20 ;
GRANT CREATE ANY OPERATOR TO role20 ;
GRANT CREATE ANY OUTLINE TO role20 ;
GRANT CREATE ANY PROCEDURE TO role20 ;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE,
  GRANTEE      => 'role20',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE_SET,
  GRANTEE      => 'role20',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE ANY SEQUENCE TO role20 ;
GRANT CREATE ANY SQL PROFILE TO role20 ;
GRANT CREATE ANY SQL TRANSLATION PROFILE TO role20 ;
GRANT CREATE ANY SYNONYM TO role20 ;
GRANT CREATE ANY TABLE TO role20 ;
GRANT CREATE ANY TRIGGER TO role20 ;
GRANT CREATE ANY TYPE TO role20 ;
GRANT CREATE ANY VIEW TO role20 ;
GRANT CREATE ASSEMBLY TO role20 ;
GRANT CREATE ATTRIBUTE DIMENSION TO role20 ;
GRANT CREATE CLUSTER TO role20 ;
GRANT CREATE CREDENTIAL TO role20 ;
GRANT CREATE CUBE TO role20 ;
GRANT CREATE CUBE BUILD PROCESS TO role20 ;
GRANT CREATE CUBE DIMENSION TO role20 ;
GRANT CREATE DATABASE LINK TO role20 ;
GRANT CREATE DIMENSION TO role20 ;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_EVALUATION_CONTEXT_OBJ,
  GRANTEE      => 'role20',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE EXTERNAL JOB TO role20 ;
GRANT CREATE HIERARCHY TO role20 ;
GRANT CREATE INDEXTYPE TO role20 ;
GRANT CREATE JOB TO role20 ;
GRANT CREATE LIBRARY TO role20 ;
GRANT CREATE LOCKDOWN PROFILE TO role20 ;
GRANT CREATE MATERIALIZED VIEW TO role20 ;
GRANT CREATE MEASURE FOLDER TO role20 ;
GRANT CREATE MINING MODEL TO role20 ;
GRANT CREATE OPERATOR TO role20 ;
GRANT CREATE PLUGGABLE DATABASE TO role20 ;
GRANT CREATE PROCEDURE TO role20 ;
GRANT CREATE PROFILE TO role20 ;
GRANT CREATE PUBLIC DATABASE LINK TO role20 ;
GRANT CREATE PUBLIC SYNONYM TO role20 ;
GRANT CREATE ROLE TO role20 ;
GRANT CREATE ROLLBACK SEGMENT TO role20 ;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_OBJ,
  GRANTEE      => 'role20',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_SET_OBJ,
  GRANTEE      => 'role20',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE SEQUENCE TO role20 ;
GRANT CREATE SESSION TO role20 ;
GRANT CREATE SQL TRANSLATION PROFILE TO role20 ;
GRANT CREATE SYNONYM TO role20 ;
GRANT CREATE TABLE TO role20 ;
GRANT CREATE TABLESPACE TO role20 ;
GRANT CREATE TRIGGER TO role20 ;
GRANT CREATE TYPE TO role20 ;
GRANT CREATE USER TO role20 ;
GRANT CREATE VIEW TO role20 ;
GRANT DEBUG ANY PROCEDURE TO role20 ;
GRANT DEBUG CONNECT SESSION TO role20 ;
GRANT DELETE ANY CUBE DIMENSION TO role20 ;
GRANT DELETE ANY MEASURE FOLDER TO role20 ;
GRANT DELETE ANY TABLE TO role20 ;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'DEQUEUE_ANY',
  GRANTEE      => 'role20',
  ADMIN_OPTION => FALSE);
END;
/
GRANT DROP ANY ANALYTIC VIEW TO role20 ;
GRANT DROP ANY ASSEMBLY TO role20 ;
GRANT DROP ANY ATTRIBUTE DIMENSION TO role20 ;
GRANT DROP ANY CLUSTER TO role20 ;
GRANT DROP ANY CONTEXT TO role20 ;
GRANT DROP ANY CUBE TO role20 ;
GRANT DROP ANY CUBE BUILD PROCESS TO role20 ;
GRANT DROP ANY CUBE DIMENSION TO role20 ;
GRANT DROP ANY DIMENSION TO role20 ;
GRANT DROP ANY DIRECTORY TO role20 ;
GRANT DROP ANY EDITION TO role20 ;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'role20',
  GRANT_OPTION => FALSE);
END;
/
GRANT DROP ANY HIERARCHY TO role20 ;
GRANT DROP ANY INDEX TO role20 ;
GRANT DROP ANY INDEXTYPE TO role20 ;
GRANT DROP ANY LIBRARY TO role20 ;
GRANT DROP ANY MATERIALIZED VIEW TO role20 ;
GRANT DROP ANY MEASURE FOLDER TO role20 ;
GRANT DROP ANY MINING MODEL TO role20 ;
GRANT DROP ANY OPERATOR TO role20 ;
GRANT DROP ANY OUTLINE TO role20 ;
GRANT DROP ANY PROCEDURE TO role20 ;
GRANT DROP ANY ROLE TO role20 ;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE,
  GRANTEE      => 'role20',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE_SET,
  GRANTEE      => 'role20',
  GRANT_OPTION => FALSE);
END;
/
GRANT DROP ANY SEQUENCE TO role20 ;
GRANT DROP ANY SQL PROFILE TO role20 ;
GRANT DROP ANY SQL TRANSLATION PROFILE TO role20 ;
GRANT DROP ANY SYNONYM TO role20 ;
GRANT DROP ANY TABLE TO role20 ;
GRANT DROP ANY TRIGGER TO role20 ;
GRANT DROP ANY TYPE TO role20 ;
GRANT DROP ANY VIEW TO role20 ;
GRANT DROP LOCKDOWN PROFILE TO role20 ;
GRANT DROP PROFILE TO role20 ;
GRANT DROP PUBLIC DATABASE LINK TO role20 ;
GRANT DROP PUBLIC SYNONYM TO role20 ;
GRANT DROP ROLLBACK SEGMENT TO role20 ;
GRANT DROP TABLESPACE TO role20 ;
GRANT DROP USER TO role20 ;
GRANT EM EXPRESS CONNECT TO role20 ;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'ENQUEUE_ANY',
  GRANTEE      => 'role20',
  ADMIN_OPTION => FALSE);
END;
/
GRANT EXECUTE ANY ASSEMBLY TO role20 ;
GRANT EXECUTE ANY CLASS TO role20 ;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'role20',
  GRANT_OPTION => FALSE);
END;
/
GRANT EXECUTE ANY INDEXTYPE TO role20 ;
GRANT EXECUTE ANY LIBRARY TO role20 ;
GRANT EXECUTE ANY OPERATOR TO role20 ;
GRANT EXECUTE ANY PROCEDURE TO role20 ;
GRANT EXECUTE ANY PROGRAM TO role20 ;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE,
  GRANTEE      => 'role20',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE_SET,
  GRANTEE      => 'role20',
  GRANT_OPTION => FALSE);
END;
/
GRANT EXECUTE ANY TYPE TO role20 ;
GRANT EXECUTE ASSEMBLY TO role20 ;
GRANT EXPORT FULL DATABASE TO role20 ;
GRANT FLASHBACK ANY TABLE TO role20 ;
GRANT FLASHBACK ARCHIVE ADMINISTER TO role20 ;
GRANT FORCE ANY TRANSACTION TO role20 ;
GRANT FORCE TRANSACTION TO role20 ;
GRANT GLOBAL QUERY REWRITE TO role20 ;
GRANT GRANT ANY OBJECT PRIVILEGE TO role20 ;
GRANT GRANT ANY PRIVILEGE TO role20 ;
GRANT GRANT ANY ROLE TO role20 ;
GRANT IMPORT FULL DATABASE TO role20 ;
GRANT INSERT ANY CUBE DIMENSION TO role20 ;
GRANT INSERT ANY MEASURE FOLDER TO role20 ;
GRANT INSERT ANY TABLE TO role20 ;
GRANT LOCK ANY TABLE TO role20 ;
GRANT LOGMINING TO role20 ;
GRANT MANAGE ANY FILE GROUP TO role20 ;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'role20',
  ADMIN_OPTION => FALSE);
END;
/
GRANT MANAGE FILE GROUP TO role20 ;
GRANT MANAGE SCHEDULER TO role20 ;
GRANT MANAGE TABLESPACE TO role20 ;
GRANT MERGE ANY VIEW TO role20 ;
GRANT ON COMMIT REFRESH TO role20 ;
GRANT QUERY REWRITE TO role20 ;
GRANT READ ANY FILE GROUP TO role20 ;
GRANT READ ANY TABLE TO role20 ;
GRANT REDEFINE ANY TABLE TO role20 ;
GRANT RESTRICTED SESSION TO role20 ;
GRANT RESUMABLE TO role20 ;
GRANT SELECT ANY CUBE TO role20 ;
GRANT SELECT ANY CUBE BUILD PROCESS TO role20 ;
GRANT SELECT ANY CUBE DIMENSION TO role20 ;
GRANT SELECT ANY DICTIONARY TO role20 ;
GRANT SELECT ANY MEASURE FOLDER TO role20 ;
GRANT SELECT ANY MINING MODEL TO role20 ;
GRANT SELECT ANY SEQUENCE TO role20 ;
GRANT SELECT ANY TABLE TO role20 ;
GRANT SELECT ANY TRANSACTION TO role20 ;
GRANT SET CONTAINER TO role20 ;
GRANT UNDER ANY TABLE TO role20 ;
GRANT UNDER ANY TYPE TO role20 ;
GRANT UNDER ANY VIEW TO role20 ;
GRANT UPDATE ANY CUBE TO role20 ;
GRANT UPDATE ANY CUBE BUILD PROCESS TO role20 ;
GRANT UPDATE ANY CUBE DIMENSION TO role20 ;
GRANT UPDATE ANY TABLE TO role20 ;
GRANT USE ANY JOB RESOURCE TO role20 ;
GRANT USE ANY SQL TRANSLATION PROFILE TO role20 ;

-- Roles granted to role20
GRANT CAPTURE_ADMIN TO role20 ;
GRANT DATAPUMP_EXP_FULL_DATABASE TO role20 ;
GRANT DATAPUMP_IMP_FULL_DATABASE TO role20 ;
GRANT EM_EXPRESS_ALL TO role20 ;
GRANT EXECUTE_CATALOG_ROLE TO role20 ;
GRANT EXP_FULL_DATABASE TO role20 ;
GRANT GATHER_SYSTEM_STATISTICS TO role20 ;
GRANT IMP_FULL_DATABASE TO role20 ;
GRANT JAVA_ADMIN TO role20 ;
GRANT OLAP_DBA TO role20 ;
GRANT OLAP_XS_ADMIN TO role20 ;
GRANT OPTIMIZER_PROCESSING_RATE TO role20 ;
GRANT SCHEDULER_ADMIN TO role20 ;
GRANT SELECT_CATALOG_ROLE TO role20 ;
GRANT WM_ADMIN_ROLE TO role20 ;
GRANT XDBADMIN TO role20 ;
GRANT XDB_SET_INVOKER TO role20 ;

-- Grantees of role20
GRANT role20 TO C##OAZ14 ;
GRANT role20 TO C##role20 ;
GRANT role20 TO HR;
GRANT role20 TO OAZ13;
GRANT role20 TO OAZ14;
GRANT role20 TO SYS WITH ADMIN OPTION ;
GRANT role20 TO SYSTEM ;
GRANT role20 TO USER1;
